Repository kowainik/summoner, pull requests merged in 2018-10, with the labels that each got.

#160 modfiy tree pretty-printer arm symbol
  src/Summoner/Tree.hs
Labels: Hacktoberfest, UX/UI

#162 Make GHC 8.6.1 the default one
  .travis.yml
  stack-8.6.1.yaml
Labels: CI, Hacktoberfest

#158 [#154] - Add Link constructor to Source data type
  CHANGELOG.md
  src/Summoner/Source.hs
  summoner.cabal
  test/Test/TomlSpec.hs
Labels: Hacktoberfest, generated project

#170 fix: change appveyor config file to 64 bit (stack & generated binary)
  CHANGELOG.md
  src/Summoner/Template.hs
Labels: CI, Hacktoberfest, windows

#165 Add HLint check to Travis CI
  .travis.yml
Labels: CI, Hacktoberfest

#188 Clean up some code with Maybes
  src/Summoner/Project.hs
  src/Summoner/Template/Doc.hs
  src/Summoner/Template/Haskell.hs
Labels: Hacktoberfest, refactoring

#190 [#189] Add tconcatMap to Summoner.Text
  CHANGELOG.md
  src/Summoner/Template/GitHub.hs
  src/Summoner/Text.hs
Labels: Hacktoberfest, refactoring
