Repository kowainik/summoner, pull requests merged in 2018-06, with the labels that each got.

#89 Update README
  README.md
Labels: bug, refactoring

#93 [#92] Remove -fhide-source-paths for GHC < 8.2
  CHANGELOG.md
  src/Summoner/Template.hs
Labels: project structure

#95 Update contributing guide
  CONTRIBUTING.md
Labels: idea

#98 Bump up to tomland-0.3
  .travis.yml
  CHANGELOG.md
  README.md
  src/Summoner/Config.hs
  stack-8.4.2.yaml
  stack-8.4.3.yaml
  stack.yaml
  summoner.cabal
Labels: config, refactoring
