Repository kowainik/summoner, pull requests merged in 2018-08, with the labels that each got.

#118 [#117] Step into created project properly
  CHANGELOG.md
  src/Summoner/Project.hs
Labels: bug

#119 [#90] Add TOML test
  CHANGELOG.md
  README.md
  src/Summoner/Config.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Template.hs
  summoner.cabal
  test/Test/TomlSpec.hs
Labels: tests

#127 [#124] Print directories bold
  CHANGELOG.md
  src/Summoner/Question.hs
  src/Summoner/Tree.hs
  summoner.cabal
Labels: beauty

#131 [#128] Make summon new command
  CHANGELOG.md
  README.md
  src/Summoner/CLI.hs
  summoner.cabal
Labels: CLI

#129 [#125] Move Decision and GhcVer into their own modules
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Decision.hs
  src/Summoner/Default.hs
  src/Summoner/GhcVer.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Question.hs
  src/Summoner/Template.hs
  summoner.cabal
  test/Test/DecisionSpec.hs
  test/Test/TomlSpec.hs
Labels: refactoring

#134 [#63] Add show commands
  CHANGELOG.md
  README.md
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/License.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Question.hs
  src/Summoner/Template.hs
  summoner.cabal
Labels: CLI

#141 [#31] Add generation of CONTRIBUTING.md file
  CHANGELOG.md
  README.md
  src/Summoner/Config.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Template.hs
  test/Test/TomlSpec.hs
Labels: config, feature, project structure

#143 [#27] Remove b-script support
  README.md
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Template.hs
  test/Test/TomlSpec.hs
Labels: beauty, docs, script

#144 [#80] Update link to demo
  CHANGELOG.md
  README.md
  stack-8.2.2.yaml
  stack.yaml
  summoner.cabal
Labels: docs
