Repository kowainik/summoner, pull requests merged in 2018-05, with the labels that each got.

#55 [#54] Rename on/off to with/without
  CHANGELOG.md
  README.md
  src/Summoner/CLI.hs
Labels: CLI

#57 [#53] Add property-based tests for semigroup/monoid laws
  src/Summoner/Project.hs
  summoner.cabal
  test/Spec.hs
  test/Test/DecisionSpec.hs
Labels: tests

#59 [#48] Add configurations, read from the file
  CHANGELOG.md
  README.md
  src/Summoner.hs
  src/Summoner/Ansi.hs
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Default.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Question.hs
  src/Summoner/Template.hs
  src/Summoner/Validation.hs
  stack.yaml
  summoner.cabal
  test/Test/DecisionSpec.hs
Labels: config, feature, idea

#64 [#60] Use universum as default prelude
  CHANGELOG.md
  src/Prelude.hs
  src/Summoner/Ansi.hs
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Default.hs
  src/Summoner/License.hs
  src/Summoner/Process.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Question.hs
  src/Summoner/Template.hs
  src/Summoner/Validation.hs
  stack.yaml
  summoner.cabal
  test/Test/DecisionSpec.hs
Labels: refactoring

#66 [#39] Add option for custom prelude
  CHANGELOG.md
  README.md
  app/Main.hs
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Template.hs
Labels: CLI, config, feature

#68 [#38] Add option for default extensions in config
  CHANGELOG.md
  README.md
  src/Summoner/Config.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Template.hs
Labels: config, feature

#69 [#65] Replace 'stack new' with our tree traversal
  src/Summoner/Project.hs
  src/Summoner/Template.hs
  src/Summoner/Tree.hs
  summoner.cabal
Labels: project structure, refactoring

#71 [#62] Print bold text
  CHANGELOG.md
  README.md
  src/Summoner/Ansi.hs
  src/Summoner/CLI.hs
  src/Summoner/Default.hs
  src/Summoner/Project.hs
  src/Summoner/Template.hs
Labels: beauty

#72 [#67] Add Answer data type
  CHANGELOG.md
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Question.hs
Labels: refactoring

#76 [#61] Add --version option
  CHANGELOG.md
  README.md
  src/Summoner/CLI.hs
  summoner.cabal
Labels: CLI, feature

#75 [#73] Write parser for CustomPrelude as table in toml
  CHANGELOG.md
  README.md
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Project.hs
  src/Summoner/Template.hs
  stack.yaml
Labels: config

#78 [#77] Build with GHC-8.4.2 on CI
  .travis.yml
  stack-8.4.2.yaml
Labels: CI

#79 [#74] Add showTree function
  CHANGELOG.md
  src/Summoner/Project.hs
  src/Summoner/Tree.hs
Labels: beauty, feature

#81 UX improvements
  src/Prelude.hs
  src/Summoner.hs
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Project.hs
  src/Summoner/Question.hs
  src/Summoner/Template.hs
  src/Summoner/Text.hs
  summoner.cabal
Labels: CLI, beauty, refactoring

#84 [#80] Add demo
  README.md
  src/Summoner/Template.hs
  summoner.cabal
Labels: CLI, beauty

#86 [#85] Remove base-noprelude dependency
  CHANGELOG.md
  app/Main.hs
  src/Prelude.hs
  src/Summoner/Ansi.hs
  src/Summoner/CLI.hs
  src/Summoner/Config.hs
  src/Summoner/Default.hs
  src/Summoner/License.hs
  src/Summoner/Process.hs
  src/Summoner/Project.hs
  src/Summoner/ProjectData.hs
  src/Summoner/Question.hs
  src/Summoner/Template.hs
  src/Summoner/Text.hs
  src/Summoner/Tree.hs
  src/Summoner/Validation.hs
  stack-8.4.2.yaml
  stack.yaml
  summoner.cabal
  test/Test/DecisionSpec.hs
Labels: refactoring

#88 [#87] Fix travis matrix
  CHANGELOG.md
  src/Summoner/Template.hs
  summoner.cabal
Labels: CI, bug
