Repository kowainik/summoner, pull requests merged in 2019-12, with the labels that each got.

#383 [#339] Support GHC-8.8
  README.md
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/Script.hs
  summoner-cli/src/Summoner/Template/Stack.hs
  summoner-cli/src/Summoner/Text.hs
  summoner-cli/test/Test/Golden.hs
  summoner-cli/test/Test/Script.hs
  summoner-cli/test/golden/fullProject/.travis.yml
  summoner-cli/test/golden/fullProject/appveyor.yml
  summoner-cli/test/golden/fullProject/fullProject.cabal
  summoner-cli/test/golden/fullProject/stack-8.6.5.yaml
  summoner-cli/test/golden/fullProject/stack.yaml
  summoner-cli/test/golden/smallProject/smallProject.cabal
Labels: generated project

#386 [#384] Test that generated projects are build on CI
  .travis.yml
Labels: tests

#387 [#385] Tests for `show` commands
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Text.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Spec.hs
  summoner-cli/test/Test/Show.hs
  summoner-tui/src/Summoner/Tui.hs
Labels: tests

#388 [#382] Improve error logging when fetching the license from GitHub
  summoner-cli/src/Summoner/License.hs
  summoner-cli/summoner.cabal
Labels: enhancement, refactoring

#389 [#362] Merge CHANGELOGs for TUI and CLI
  .github/pull_request_template.md
  CHANGELOG.md
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/Script.hs
  summoner-cli/test/Test/Show.hs
  summoner-cli/test/golden/fullProject/stack-8.6.5.yaml
  summoner-cli/test/golden/fullProject/stack.yaml
  summoner-tui/CHANGELOG.md
  summoner-tui/summoner-tui.cabal
Labels: docs

#391 Improve CHANGELOG a bit
  CHANGELOG.md
Labels: docs

#390 Polish README a bit
  README.md
Labels: docs
