Repository kowainik/summoner, pull requests merged in 2019-04, with the labels that each got.

#298 Add ghc864
  .travis.yml
  stack.yaml
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/Script.hs
  summoner-cli/test/golden/fullProject/.travis.yml
  summoner-cli/test/golden/fullProject/fullProject.cabal
  summoner-cli/test/golden/fullProject/stack.yaml
  summoner-cli/test/golden/smallProject/smallProject.cabal
Labels: enhancement

#299 [#280] Support appveyor for cabal
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/test/golden/fullProject/appveyor.yml
  summoner-tui/CHANGELOG.md
  summoner-tui/src/Summoner/Tui/Form.hs
Labels: CI, windows

#302 [#297] Strip project description in TUI
  summoner-tui/CHANGELOG.md
  summoner-tui/src/Summoner/Tui/Kit.hs
Labels: TUI, bug, enhancement

#305 [#261] Try to guess user name and email from .gitconfig
  README.md
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack.yaml
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/summoner.cabal
Labels: config

#307 [#304] Bump up to relude-0.5.0 and brick-0.47
  .travis.yml
  appveyor.yml
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack.yaml
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/golden/fullProject/appveyor.yml
  summoner-tui/src/Summoner/Tui.hs
  summoner-tui/summoner-tui.cabal
Labels: refactoring

#306 [#303] Add noUpload option to toml config
  README.md
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/Config.hs
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/test/Test/TomlSpec.hs
  summoner-tui/src/Summoner/Tui.hs
  summoner-tui/src/Summoner/Tui/Kit.hs
Labels: config, feature

#309 Add golden files to extra-source-files
  summoner-cli/CHANGELOG.md
  summoner-cli/summoner.cabal
Labels: enhancement, tests
