Repository kowainik/summoner, pull requests merged in 2019-01, with the labels that each got.

#274 [#270] Add golden tests to data-dir
  summoner-cli/summoner.cabal
Labels: enhancement, tests

#277 [#268] Simplify adding custom prelude in CLI
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/Project.hs
Labels: CLI

#276 [#275] [#272] New simple travis settings
  .travis.yml
Labels: CI

#278 [#272] Simplify Travis for summoner even more
  .travis.yml
  stack.yaml
Labels: CI

#279 [#272] [#275] Travis improvements for generated project
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/Default.hs
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/test/golden/fullProject/.travis.yml
Labels: CI, help wanted

#287 [#286] Bump up to tomland-1.0.0
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack.yaml
  summoner-cli/CHANGELOG.md
  summoner-cli/src/Summoner/Config.hs
  summoner-cli/src/Summoner/Source.hs
  summoner-cli/summoner.cabal
Labels: refactoring
