Repository kowainik/summoner, pull requests merged in 2020-05, with the labels that each got.

#456 Make better links to ToC from everywhere
  README.md
Labels: docs

#458 [#459] [#455] Use tomland-1.3.0.0, validation-selective-0.1.0.0
  CHANGELOG.md
  cabal.project
  stack.yaml
  summoner-cli/src/Summoner/CustomPrelude.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/TomlSpec.hs
  summoner-tui/summoner-tui.cabal
Labels: library

#461 [#452] Use colourista-0.1.0.0
  CHANGELOG.md
  stack.yaml
  summoner-cli/src/Summoner.hs
  summoner-cli/src/Summoner/Ansi.hs
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/CustomPrelude.hs
  summoner-cli/src/Summoner/License.hs
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Question.hs
  summoner-cli/src/Summoner/Source.hs
  summoner-cli/summoner.cabal
  summoner-tui/src/Summoner/Tui.hs
  summoner-tui/summoner-tui.cabal
Labels: UX/UI, library, refactoring

#462 [#460] Use relude-0.7.0.0
  .travis.yml
  CHANGELOG.md
  stack.yaml
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Question.hs
  summoner-cli/src/Summoner/Template.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/src/Summoner/Template/Mempty.hs
  summoner-cli/summoner.cabal
  summoner-tui/summoner-tui.cabal
Labels: library, refactoring

#463 [#443] Test Summoner with GHC-8.10
  .github/workflows/ci.yml
  CHANGELOG.md
  summoner-cli/summoner.cabal
  summoner-tui/summoner-tui.cabal
Labels: CI, library, refactoring

#468 [#467] Allow aeson-1.5.0.0
  .github/workflows/ci.yml
  summoner-cli/summoner.cabal
Labels: library

#470 [#469] Brick-0.54
  CHANGELOG.md
  summoner-cli/summoner.cabal
  summoner-tui/summoner-tui.cabal
Labels: library
