Repository kowainik/summoner, pull requests merged in 2020-06, with the labels that each got.

#471 Add configuration for Headroom
  .headroom.yaml
  headroom-templates/haskell.mustache
Labels: docs

#473 [#466] Add `--test-dhow-details=direct` to CI tests
  .github/workflows/ci.yml
  CHANGELOG.md
  summoner-cli/examples/cabal-full/.github/workflows/ci.yml
  summoner-cli/examples/cabal-full/.travis.yml
  summoner-cli/examples/full-batteries/.github/workflows/ci.yml
  summoner-cli/examples/full-batteries/.travis.yml
  summoner-cli/src/Summoner/Template/GitHub.hs
Labels: CI, generated project

#457 Use headroom to prettify headers
  summoner-cli/src/Summoner.hs
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/Config.hs
  summoner-cli/src/Summoner/CustomPrelude.hs
  summoner-cli/src/Summoner/Decision.hs
  summoner-cli/src/Summoner/Default.hs
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/License.hs
  summoner-cli/src/Summoner/Mode.hs
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Question.hs
  summoner-cli/src/Summoner/Settings.hs
  summoner-cli/src/Summoner/Source.hs
  summoner-cli/src/Summoner/Template.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/Doc.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/src/Summoner/Template/Haskell.hs
  summoner-cli/src/Summoner/Template/Script.hs
  summoner-cli/src/Summoner/Template/Stack.hs
  summoner-cli/src/Summoner/Text.hs
  summoner-cli/src/Summoner/Tree.hs
  summoner-tui/src/Summoner/Tui.hs
  summoner-tui/src/Summoner/Tui/Field.hs
  summoner-tui/src/Summoner/Tui/Form.hs
  summoner-tui/src/Summoner/Tui/GroupBorder.hs
  summoner-tui/src/Summoner/Tui/Kit.hs
  summoner-tui/src/Summoner/Tui/Validation.hs
  summoner-tui/src/Summoner/Tui/Widget.hs
Labels: docs

#475 [#444] Support GHC-8.10 in generated projects
  .github/workflows/ci.yml
  .travis.yml
  CHANGELOG.md
  README.md
  summoner-cli/examples/cabal-full/.github/workflows/ci.yml
  summoner-cli/examples/cabal-full/.travis.yml
  summoner-cli/examples/cabal-full/appveyor.yml
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
  summoner-cli/examples/full-batteries/.github/workflows/ci.yml
  summoner-cli/examples/full-batteries/.travis.yml
  summoner-cli/examples/full-batteries/appveyor.yml
  summoner-cli/examples/full-batteries/full-batteries.cabal
  summoner-cli/examples/full-batteries/stack-8.8.3.yaml
  summoner-cli/examples/full-batteries/stack.yaml
  summoner-cli/examples/stack-full/.travis.yml
  summoner-cli/examples/stack-full/stack-8.8.3.yaml
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/examples/stack-full/stack.yaml
  summoner-cli/examples/summoner-default.toml
  summoner-cli/src/Summoner/Default.hs
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/test/Test/Script.hs
  summoner-cli/test/Test/Show.hs
Labels: CI, enhancement, generated project
