Repository kowainik/summoner, pull requests merged in 2020-03, with the labels that each got.

#427 Use hspec-hedgehog for property tests
  stack.yaml
  summoner-cli/summoner.cabal
  summoner-cli/test/Spec.hs
  summoner-cli/test/Test/DecisionSpec.hs
  summoner-cli/test/Test/TomlSpec.hs
Labels: library, tests

#425 Better GitHub releases
  .github/workflows/ci.yml
  .travis.yml
  appveyor.yml
Labels: CI

#428 Fix some warnings
  summoner-cli/app/Cli.hs
  summoner-cli/test/Test/DecisionSpec.hs
  summoner-tui/app/Tui.hs
Labels: refactoring

#431 [#429] Move to GHC-8.8.3
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  stack.yaml
  summoner-cli/examples/cabal-full/.github/workflows/ci.yml
  summoner-cli/examples/cabal-full/.travis.yml
  summoner-cli/examples/cabal-full/appveyor.yml
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
  summoner-cli/examples/full-batteries/.github/workflows/ci.yml
  summoner-cli/examples/full-batteries/.travis.yml
  summoner-cli/examples/full-batteries/appveyor.yml
  summoner-cli/examples/full-batteries/full-batteries.cabal
  summoner-cli/examples/full-batteries/stack.yaml
  summoner-cli/examples/stack-full/.travis.yml
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/examples/stack-full/stack.yaml
  summoner-cli/examples/summoner-default.toml
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/Show.hs
  summoner-tui/summoner-tui.cabal
Labels: CI, generated project

#432 [#430] Allow-failures for old GHC on Stack at TravisCI
  CHANGELOG.md
  README.md
  stack.yaml
  summoner-cli/examples/cabal-full/.travis.yml
  summoner-cli/examples/full-batteries/.travis.yml
  summoner-cli/examples/full-batteries/stack.yaml
  summoner-cli/examples/stack-full/.travis.yml
  summoner-cli/examples/stack-full/stack.yaml
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/test/Test/Show.hs
Labels: CI, generated project

#437 [#436] Remove GHC-8.2.2 check from the CI
  .github/workflows/ci.yml
  .travis.yml
  summoner-cli/summoner.cabal
  summoner-tui/summoner-tui.cabal
Labels: CI, library

#435 [#434] Move to 'validation-selective'
  CHANGELOG.md
  stack.yaml
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/Config.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/TomlSpec.hs
  summoner-tui/src/Summoner/Tui/Validation.hs
  summoner-tui/summoner-tui.cabal
Labels: library, refactoring

#438 [#433] Add missing files to extra-source-files
  summoner-cli/summoner.cabal
Labels: tests

#439 Prepare changelog for the 2.0 release
  CHANGELOG.md
  summoner-cli/src/Summoner/License.hs
  summoner-cli/src/Summoner/Source.hs
  summoner-cli/summoner.cabal
  summoner-tui/summoner-tui.cabal
Labels: docs

#440 Add installation instructions for Mac and Ubuntu
  README.md
Labels: CLI, TUI, docs

#441 [#423] Rerecord demo videos
  README.md
Labels: docs
