Repository kowainik/summoner, pull requests merged in 2020-07, with the labels that each got.

#479 [#476] Swap aeson with microaeson
  CHANGELOG.md
  stack.yaml
  summoner-cli/src/Summoner/Config.hs
  summoner-cli/src/Summoner/License.hs
  summoner-cli/summoner.cabal
Labels: library

#481 Remove Stackage instructions
  README.md
Labels: docs

#483 [#477] Remove `neat-interpolation`
  CHANGELOG.md
  summoner-cli/examples/cabal-full/.travis.yml
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
  summoner-cli/examples/full-batteries/.travis.yml
  summoner-cli/examples/full-batteries/full-batteries.cabal
  summoner-cli/examples/stack-full/.travis.yml
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/Default.hs
  summoner-cli/src/Summoner/Project.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/src/Summoner/Template/Haskell.hs
  summoner-cli/src/Summoner/Template/Script.hs
  summoner-cli/src/Summoner/Text.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/Golden.hs
  summoner-cli/test/Test/Script.hs
  summoner-cli/test/Test/Show.hs
Labels: library, refactoring, tests

#486 [#442] Get current year with the timezone in mind
  CHANGELOG.md
  summoner-cli/src/Summoner/Default.hs
Labels: enhancement

#488 [#446] Add link to README in cabal description link
  CHANGELOG.md
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
  summoner-cli/examples/full-batteries/full-batteries.cabal
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/src/Summoner/Template/Cabal.hs
Labels: generated project

#490 [#453] Drop GHC-7.10 support
  CHANGELOG.md
  README.md
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/test/Test/Golden.hs
  summoner-cli/test/Test/Show.hs
Labels: generated project, question

#492 [#484] Generated source files improvements
  CHANGELOG.md
  summoner-cli/examples/cabal-full/app/Main.hs
  summoner-cli/examples/cabal-full/benchmark/Main.hs
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-full/src/CabalFull.hs
  summoner-cli/examples/cabal-full/test/Spec.hs
  summoner-cli/examples/cabal-minimal/app/Main.hs
  summoner-cli/examples/full-batteries/app/Main.hs
  summoner-cli/examples/full-batteries/benchmark/Main.hs
  summoner-cli/examples/full-batteries/full-batteries.cabal
  summoner-cli/examples/full-batteries/src/FullBatteries.hs
  summoner-cli/examples/full-batteries/test/Spec.hs
  summoner-cli/examples/stack-full/app/Main.hs
  summoner-cli/examples/stack-full/benchmark/Main.hs
  summoner-cli/examples/stack-full/src/StackFull.hs
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/examples/stack-full/test/Spec.hs
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/Haskell.hs
Labels: enhancement, generated project
