Repository kowainik/summoner, pull requests merged in 2020-08, with the labels that each got.

#494 [#482] Add GHC options to generate the HIE files
  .gitignore
  CHANGELOG.md
  README.md
  summoner-cli/examples/cabal-full/.gitignore
  summoner-cli/examples/cabal-full/cabal-full.cabal
  summoner-cli/examples/cabal-minimal/cabal-minimal.cabal
  summoner-cli/examples/full-batteries/.gitignore
  summoner-cli/examples/stack-full/.gitignore
  summoner-cli/examples/stack-full/stack-full.cabal
  summoner-cli/src/Summoner/Template/Cabal.hs
  summoner-cli/src/Summoner/Template/GitHub.hs
  summoner-cli/summoner.cabal
  summoner-tui/summoner-tui.cabal
Labels: generated project, ghc

#498 [#496] Run Stan on Summoner and fix observations
  summoner-cli/src/Summoner/CLI.hs
  summoner-cli/src/Summoner/GhcVer.hs
  summoner-cli/src/Summoner/Tree.hs
  summoner-cli/summoner.cabal
  summoner-cli/test/Test/TomlSpec.hs
  summoner-tui/src/Summoner/Tui.hs
  summoner-tui/src/Summoner/Tui/Form.hs
  summoner-tui/src/Summoner/Tui/Validation.hs
Labels: enhancement, refactoring

#500 [#464] Build only `master` branch on AppVeyor
  appveyor.yml
  summoner-cli/examples/cabal-full/appveyor.yml
  summoner-cli/examples/full-batteries/appveyor.yml
  summoner-cli/examples/stack-full/appveyor.yml
  summoner-cli/src/Summoner/Template/GitHub.hs
Labels: CI, windows
